version: '3'

services:
#  mysql:
#    image: 'mysql:latest'
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_DATABASE=douyin
##      - MYSQL_USER=root
#      - MYSQL_ROOT_PASSWORD=111111
#      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
